-- 1. Update Posts Table
-- Safe update: Check if column exists, if not add it
do $$ 
begin 
  if not exists (select 1 from information_schema.columns where table_name='posts' and column_name='user_id') then
    alter table public.posts add column user_id uuid references auth.users(id);
  end if;
end $$;

-- 2. Create Likes Table
create table if not exists public.post_likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) not null,
  post_id bigint references public.posts(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, post_id)
);

-- 3. Create Bookmarks Table
create table if not exists public.bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) not null,
  post_id bigint references public.posts(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, post_id)
);

-- 4. Enable RLS
alter table public.post_likes enable row level security;
alter table public.bookmarks enable row level security;

-- 5. Policies for Likes (Drop first to avoid errors)
drop policy if exists "Public view likes" on public.post_likes;
drop policy if exists "Authenticated create like" on public.post_likes;
drop policy if exists "Authenticated delete like" on public.post_likes;

create policy "Public view likes" on public.post_likes for select using (true);
create policy "Authenticated create like" on public.post_likes for insert to authenticated with check (auth.uid() = user_id);
create policy "Authenticated delete like" on public.post_likes for delete to authenticated using (auth.uid() = user_id);

-- 6. Policies for Bookmarks (Drop first to avoid errors)
drop policy if exists "Public view bookmarks" on public.bookmarks;
drop policy if exists "Owner view bookmarks" on public.bookmarks;
drop policy if exists "Authenticated create bookmark" on public.bookmarks;
drop policy if exists "Authenticated delete bookmark" on public.bookmarks;

create policy "Public view bookmarks" on public.bookmarks for select using (true); 
create policy "Owner view bookmarks" on public.bookmarks for select using (auth.uid() = user_id);
create policy "Authenticated create bookmark" on public.bookmarks for insert to authenticated with check (auth.uid() = user_id);
create policy "Authenticated delete bookmark" on public.bookmarks for delete to authenticated using (auth.uid() = user_id);

-- 7. Update Post Policies
drop policy if exists "Authenticated insert posts" on public.posts;
create policy "Authenticated insert posts" on public.posts for insert to authenticated with check (auth.uid() = user_id);

-- 8. Allow users to delete their own posts
drop policy if exists "Authenticated delete posts" on public.posts;
create policy "Authenticated delete posts" on public.posts for delete to authenticated using (auth.uid() = user_id);
