-- Create a table for Public Posts
create table public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  category text not null,
  author text not null default 'Anonymous',
  role text not null default 'guest',
  likes numeric default 0,
  tags text[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.posts enable row level security;

-- Create Policy: Allow Public Read Access
create policy "Allow Public Read Access"
on public.posts
for select
to anon
using (true);

-- Create Policy: Allow Public Insert Access (For Demo purposes, usually requires auth)
create policy "Allow Public Insert Access"
on public.posts
for insert
to anon
with check (true);

-- Create Policy: Allow Public Update (Likes)
create policy "Allow Public Update Likes"
on public.posts
for update
to anon
using (true);
